[hekad]
maxprocs = 1

[KafkaInput]
type = "KafkaInput"
topic = "%ENV[KAFKA_INPUT_TOPIC]"
group = "%ENV[KAFKA_INPUT_GROUP]"
addrs = {{REPLACE_CSV|KAFKA_INPUT_BROKER}}
decoder = "log_batwara"

[log_batwara]
type = "SandboxDecoder"
filename = "lua_custom/log_batwara.lua"

[PayloadEncoder]
append_newlines = false

{{TEMPLATE}}
[KafkaOutput-{{value}}]
type = "KafkaOutput"
message_matcher = "Type == '{{value}}'"
topic = "{{key}}"
addrs = {{REPLACE_CSV|KAFKA_OUTPUT_BROKER}}
encoder = "PayloadEncoder"

{{TEMPLATE}}

[KafkaOutput]
type = "KafkaOutput"
message_matcher = "Type == '%ENV[KAFKA_DEFAULT_TOPIC]'"
topic = "%ENV[KAFKA_DEFAULT_TOPIC]"
addrs = {{REPLACE_CSV|KAFKA_OUTPUT_BROKER}}
encoder = "PayloadEncoder"
