[hekad]
maxprocs = 1
base_dir = "/heka/log"

[dockerlogs]
type = "LogstreamerInput"
log_directory = "/var/lib/docker/containers"
file_match = '(?P<ContainerId>[^/]+)/(?P<ContainerId>[^/]+)-json.log.?(?P<Seq>\d*)?'
rescan_interval = '3s'
priority = ["^Seq"]
differentiator = ["container_id.", "ContainerId"]
decoder = 'GelfDecoder'

[GelfDecoder]
type = "SandboxDecoder"
filename = "lua_custom/gelf_filter.lua"

[PayloadEncoder]
append_newlines = false

{{TEMPLATE}}
[KafkaOutput-{{key}}]
type = "KafkaOutput"
message_matcher = "Type == '{{key}}'"
topic = "{{key}}"
addrs = {{REPLACE_CSV|KAFKA_OUTPUT_BROKER}}
encoder = "PayloadEncoder"
compression_codec = "Snappy"

{{TEMPLATE}}

[KafkaOutput]
type = "KafkaOutput"
message_matcher = "Type == '%ENV[KAFKA_DEFAULT_TOPIC]'"
topic = "%ENV[KAFKA_DEFAULT_TOPIC]"
addrs = {{REPLACE_CSV|KAFKA_OUTPUT_BROKER}}
encoder = "PayloadEncoder"
compression_codec = "Snappy"

[DashboardOutput]
ticker_interval = 5
